accounts:
  - name: alice
    coins: [ "2000000000nimv", "200000000stake" ]
  - name: bob
    coins: [ "3000000000nimv", "100000000stake" ]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
init:
  app:
    minimum-gas-prices: 0.1nimv
  api:
    enable: true
  json-rpc:
    address: "0.0.0.0:8545"     # change the JSON-RPC address and port
    ws-address: "0.0.0.0:8546"
genesis:
  app_state:
    bank:
      denom_metadata:
        - base: nimv
          display: imversed
          name: imversed
          symbol: imv
          description: The native staking token of the Imversed.
          denom_units:
            - denom: nimv
              exponent: 0
              aliases: [ "nimv", "nanoimversed" ]
            - denom: imversed
              exponent: 6
              aliases: [ "imv", "imversed" ]
    currency:
      params:
        txMintCurrencyCost: "10000000"
