// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xverse/verse.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Verse struct {
	Owner             string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name              string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon              string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description       string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SmartContracts    []string `protobuf:"bytes,5,rep,name=smart_contracts,json=smartContracts,proto3" json:"smart_contracts,omitempty"`
	Oracle            string   `protobuf:"bytes,6,opt,name=oracle,proto3" json:"oracle,omitempty"`
	AuthenticatedKeys []string `protobuf:"bytes,7,rep,name=authenticated_keys,json=authenticatedKeys,proto3" json:"authenticated_keys,omitempty"`
	Dao               string   `protobuf:"bytes,8,opt,name=dao,proto3" json:"dao,omitempty"`
	DaoHeight         int64    `protobuf:"varint,9,opt,name=dao_height,json=daoHeight,proto3" json:"dao_height,omitempty"`
}

func (m *Verse) Reset()         { *m = Verse{} }
func (m *Verse) String() string { return proto.CompactTextString(m) }
func (*Verse) ProtoMessage()    {}
func (*Verse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cc615859ff75156, []int{0}
}
func (m *Verse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Verse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Verse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Verse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verse.Merge(m, src)
}
func (m *Verse) XXX_Size() int {
	return m.Size()
}
func (m *Verse) XXX_DiscardUnknown() {
	xxx_messageInfo_Verse.DiscardUnknown(m)
}

var xxx_messageInfo_Verse proto.InternalMessageInfo

func (m *Verse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Verse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Verse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Verse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Verse) GetSmartContracts() []string {
	if m != nil {
		return m.SmartContracts
	}
	return nil
}

func (m *Verse) GetOracle() string {
	if m != nil {
		return m.Oracle
	}
	return ""
}

func (m *Verse) GetAuthenticatedKeys() []string {
	if m != nil {
		return m.AuthenticatedKeys
	}
	return nil
}

func (m *Verse) GetDao() string {
	if m != nil {
		return m.Dao
	}
	return ""
}

func (m *Verse) GetDaoHeight() int64 {
	if m != nil {
		return m.DaoHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Verse)(nil), "imversed.xverse.Verse")
}

func init() { proto.RegisterFile("xverse/verse.proto", fileDescriptor_3cc615859ff75156) }

var fileDescriptor_3cc615859ff75156 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0xa6, 0xad, 0x66, 0x05, 0xab, 0x43, 0x91, 0x45, 0x30, 0x04, 0x2f, 0x16, 0xc4,
	0xe6, 0xe0, 0x1b, 0x28, 0x82, 0xe0, 0xad, 0x07, 0x0f, 0x5e, 0xca, 0x76, 0x33, 0x24, 0x8b, 0x26,
	0x53, 0x76, 0xb7, 0xda, 0xbe, 0x81, 0x47, 0x1f, 0xcb, 0x63, 0x8f, 0x1e, 0xa5, 0x7d, 0x11, 0xc9,
	0xa4, 0x45, 0xbd, 0x2c, 0xff, 0x7c, 0xdf, 0xf2, 0x1f, 0x7e, 0x01, 0x8b, 0x57, 0xb4, 0x0e, 0x53,
	0x7e, 0x47, 0x33, 0x4b, 0x9e, 0xa0, 0x6f, 0x4a, 0x3e, 0xb3, 0x51, 0x23, 0x4f, 0x07, 0x39, 0xe5,
	0xc4, 0x2e, 0xad, 0x53, 0xf3, 0xed, 0xfc, 0xbd, 0x2d, 0xba, 0x8f, 0xb5, 0x87, 0x81, 0xe8, 0xd2,
	0x5b, 0x85, 0x56, 0x06, 0x49, 0x30, 0x8c, 0xc6, 0xcd, 0x01, 0x20, 0x3a, 0x95, 0x2a, 0x51, 0xb6,
	0x19, 0x72, 0xae, 0x99, 0xd1, 0x54, 0xc9, 0xb0, 0x61, 0x75, 0x86, 0x44, 0x1c, 0x64, 0xe8, 0xb4,
	0x35, 0x33, 0x6f, 0xa8, 0x92, 0x1d, 0x56, 0x7f, 0x11, 0x5c, 0x88, 0xbe, 0x2b, 0x95, 0xf5, 0x13,
	0x4d, 0x95, 0xb7, 0x4a, 0x7b, 0x27, 0xbb, 0x49, 0x38, 0x8c, 0xc6, 0x87, 0x8c, 0x6f, 0x77, 0x14,
	0x4e, 0x44, 0x8f, 0xac, 0xd2, 0x2f, 0x28, 0x7b, 0xdc, 0xb2, 0xbd, 0xe0, 0x4a, 0x80, 0x9a, 0xfb,
	0x02, 0x2b, 0x6f, 0xb4, 0xf2, 0x98, 0x4d, 0x9e, 0x71, 0xe9, 0xe4, 0x1e, 0x77, 0x1c, 0xff, 0x33,
	0x0f, 0xb8, 0x74, 0x70, 0x24, 0xc2, 0x4c, 0x91, 0xdc, 0xe7, 0x8e, 0x3a, 0xc2, 0x99, 0x10, 0x99,
	0xa2, 0x49, 0x81, 0x26, 0x2f, 0xbc, 0x8c, 0x92, 0x60, 0x18, 0x8e, 0xa3, 0x4c, 0xd1, 0x3d, 0x83,
	0x9b, 0xbb, 0xcf, 0x75, 0x1c, 0xac, 0xd6, 0x71, 0xf0, 0xbd, 0x8e, 0x83, 0x8f, 0x4d, 0xdc, 0x5a,
	0x6d, 0xe2, 0xd6, 0xd7, 0x26, 0x6e, 0x3d, 0x5d, 0xe6, 0xc6, 0x17, 0xf3, 0xe9, 0x48, 0x53, 0x99,
	0xee, 0x66, 0xfd, 0x0d, 0x8b, 0x74, 0x3b, 0xbf, 0x5f, 0xce, 0xd0, 0x4d, 0x7b, 0x3c, 0xec, 0xf5,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x9f, 0x41, 0xeb, 0x95, 0x01, 0x00, 0x00,
}

func (m *Verse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Verse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Verse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DaoHeight != 0 {
		i = encodeVarintVerse(dAtA, i, uint64(m.DaoHeight))
		i--
		dAtA[i] = 0x48
	}
	if len(m.Dao) > 0 {
		i -= len(m.Dao)
		copy(dAtA[i:], m.Dao)
		i = encodeVarintVerse(dAtA, i, uint64(len(m.Dao)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.AuthenticatedKeys) > 0 {
		for iNdEx := len(m.AuthenticatedKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AuthenticatedKeys[iNdEx])
			copy(dAtA[i:], m.AuthenticatedKeys[iNdEx])
			i = encodeVarintVerse(dAtA, i, uint64(len(m.AuthenticatedKeys[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Oracle) > 0 {
		i -= len(m.Oracle)
		copy(dAtA[i:], m.Oracle)
		i = encodeVarintVerse(dAtA, i, uint64(len(m.Oracle)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SmartContracts) > 0 {
		for iNdEx := len(m.SmartContracts) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SmartContracts[iNdEx])
			copy(dAtA[i:], m.SmartContracts[iNdEx])
			i = encodeVarintVerse(dAtA, i, uint64(len(m.SmartContracts[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintVerse(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Icon) > 0 {
		i -= len(m.Icon)
		copy(dAtA[i:], m.Icon)
		i = encodeVarintVerse(dAtA, i, uint64(len(m.Icon)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintVerse(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintVerse(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVerse(dAtA []byte, offset int, v uint64) int {
	offset -= sovVerse(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Verse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovVerse(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovVerse(uint64(l))
	}
	l = len(m.Icon)
	if l > 0 {
		n += 1 + l + sovVerse(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovVerse(uint64(l))
	}
	if len(m.SmartContracts) > 0 {
		for _, s := range m.SmartContracts {
			l = len(s)
			n += 1 + l + sovVerse(uint64(l))
		}
	}
	l = len(m.Oracle)
	if l > 0 {
		n += 1 + l + sovVerse(uint64(l))
	}
	if len(m.AuthenticatedKeys) > 0 {
		for _, s := range m.AuthenticatedKeys {
			l = len(s)
			n += 1 + l + sovVerse(uint64(l))
		}
	}
	l = len(m.Dao)
	if l > 0 {
		n += 1 + l + sovVerse(uint64(l))
	}
	if m.DaoHeight != 0 {
		n += 1 + sovVerse(uint64(m.DaoHeight))
	}
	return n
}

func sovVerse(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVerse(x uint64) (n int) {
	return sovVerse(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Verse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVerse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Verse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Verse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Icon", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Icon = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SmartContracts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SmartContracts = append(m.SmartContracts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oracle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Oracle = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthenticatedKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthenticatedKeys = append(m.AuthenticatedKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dao", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVerse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVerse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dao = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoHeight", wireType)
			}
			m.DaoHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DaoHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVerse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVerse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVerse(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVerse
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVerse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVerse
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVerse
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVerse
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVerse        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVerse          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVerse = fmt.Errorf("proto: unexpected end of group")
)
