// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: verse/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateVerse struct {
	Sender      string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Icon        string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *MsgCreateVerse) Reset()         { *m = MsgCreateVerse{} }
func (m *MsgCreateVerse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateVerse) ProtoMessage()    {}
func (*MsgCreateVerse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b1ed414ec89264, []int{0}
}
func (m *MsgCreateVerse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateVerse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateVerse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateVerse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateVerse.Merge(m, src)
}
func (m *MsgCreateVerse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateVerse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateVerse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateVerse proto.InternalMessageInfo

func (m *MsgCreateVerse) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgCreateVerse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *MsgCreateVerse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MsgCreateVerseResponse struct {
}

func (m *MsgCreateVerseResponse) Reset()         { *m = MsgCreateVerseResponse{} }
func (m *MsgCreateVerseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateVerseResponse) ProtoMessage()    {}
func (*MsgCreateVerseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b1ed414ec89264, []int{1}
}
func (m *MsgCreateVerseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateVerseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateVerseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateVerseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateVerseResponse.Merge(m, src)
}
func (m *MsgCreateVerseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateVerseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateVerseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateVerseResponse proto.InternalMessageInfo

type MsgAddAssetToVerse struct {
	Sender       string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	VerseName    string `protobuf:"bytes,2,opt,name=verse_name,json=verseName,proto3" json:"verse_name,omitempty"`
	AssetType    string `protobuf:"bytes,3,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	AssetId      string `protobuf:"bytes,4,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AssetCreator string `protobuf:"bytes,5,opt,name=asset_creator,json=assetCreator,proto3" json:"asset_creator,omitempty"`
	VerseCreator string `protobuf:"bytes,6,opt,name=verse_creator,json=verseCreator,proto3" json:"verse_creator,omitempty"`
}

func (m *MsgAddAssetToVerse) Reset()         { *m = MsgAddAssetToVerse{} }
func (m *MsgAddAssetToVerse) String() string { return proto.CompactTextString(m) }
func (*MsgAddAssetToVerse) ProtoMessage()    {}
func (*MsgAddAssetToVerse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b1ed414ec89264, []int{2}
}
func (m *MsgAddAssetToVerse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddAssetToVerse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddAssetToVerse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddAssetToVerse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddAssetToVerse.Merge(m, src)
}
func (m *MsgAddAssetToVerse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddAssetToVerse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddAssetToVerse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddAssetToVerse proto.InternalMessageInfo

func (m *MsgAddAssetToVerse) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgAddAssetToVerse) GetVerseName() string {
	if m != nil {
		return m.VerseName
	}
	return ""
}

func (m *MsgAddAssetToVerse) GetAssetType() string {
	if m != nil {
		return m.AssetType
	}
	return ""
}

func (m *MsgAddAssetToVerse) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *MsgAddAssetToVerse) GetAssetCreator() string {
	if m != nil {
		return m.AssetCreator
	}
	return ""
}

func (m *MsgAddAssetToVerse) GetVerseCreator() string {
	if m != nil {
		return m.VerseCreator
	}
	return ""
}

type MsgAddAssetToVerseResponse struct {
}

func (m *MsgAddAssetToVerseResponse) Reset()         { *m = MsgAddAssetToVerseResponse{} }
func (m *MsgAddAssetToVerseResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddAssetToVerseResponse) ProtoMessage()    {}
func (*MsgAddAssetToVerseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b1ed414ec89264, []int{3}
}
func (m *MsgAddAssetToVerseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddAssetToVerseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddAssetToVerseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddAssetToVerseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddAssetToVerseResponse.Merge(m, src)
}
func (m *MsgAddAssetToVerseResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddAssetToVerseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddAssetToVerseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddAssetToVerseResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateVerse)(nil), "imversed.verse.MsgCreateVerse")
	proto.RegisterType((*MsgCreateVerseResponse)(nil), "imversed.verse.MsgCreateVerseResponse")
	proto.RegisterType((*MsgAddAssetToVerse)(nil), "imversed.verse.MsgAddAssetToVerse")
	proto.RegisterType((*MsgAddAssetToVerseResponse)(nil), "imversed.verse.MsgAddAssetToVerseResponse")
}

func init() { proto.RegisterFile("verse/tx.proto", fileDescriptor_28b1ed414ec89264) }

var fileDescriptor_28b1ed414ec89264 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0xd9, 0x3f, 0xfc, 0x51, 0x06, 0xc5, 0x64, 0x0f, 0xa4, 0x12, 0xdd, 0x90, 0x9a, 0x18,
	0xc3, 0xa1, 0x24, 0xfa, 0x04, 0x88, 0x17, 0x0f, 0x78, 0x20, 0xe8, 0xc1, 0x83, 0xa4, 0x74, 0x27,
	0xb5, 0x87, 0x76, 0x9b, 0xee, 0x6a, 0xe0, 0x2d, 0x7c, 0x23, 0xaf, 0xde, 0xe4, 0xe8, 0xd1, 0xc0,
	0x8b, 0x98, 0x4e, 0xdb, 0x08, 0x68, 0xf0, 0xd4, 0xdd, 0xdf, 0xf7, 0x75, 0xe6, 0xdb, 0xd9, 0x85,
	0xc6, 0x33, 0x26, 0x1a, 0xbb, 0x66, 0xea, 0xc4, 0x89, 0x32, 0x8a, 0x37, 0x82, 0x90, 0x88, 0x74,
	0xe8, 0x63, 0x3f, 0x40, 0x63, 0xa0, 0xfd, 0x7e, 0x82, 0xae, 0xc1, 0xbb, 0x94, 0xf0, 0x26, 0x54,
	0x35, 0x46, 0x12, 0x13, 0x8b, 0xb5, 0xd9, 0x59, 0x6d, 0x98, 0xef, 0x38, 0x87, 0x4a, 0xe0, 0xa9,
	0xc8, 0x2a, 0x13, 0xa5, 0x35, 0x6f, 0x43, 0x5d, 0xa2, 0xf6, 0x92, 0x20, 0x36, 0x81, 0x8a, 0xac,
	0x0a, 0x49, 0xab, 0xc8, 0xb6, 0xa0, 0xb9, 0x5e, 0x7f, 0x88, 0x3a, 0x56, 0x91, 0x46, 0xfb, 0x9d,
	0x01, 0x1f, 0x68, 0xbf, 0x27, 0x65, 0x4f, 0x6b, 0x34, 0x23, 0xb5, 0xbd, 0xfd, 0x31, 0x00, 0x25,
	0x1e, 0x47, 0x6e, 0x88, 0xd6, 0x3f, 0xd2, 0x6a, 0x44, 0x6e, 0xdc, 0x10, 0x53, 0xd9, 0x4d, 0xcb,
	0x8c, 0xcd, 0x2c, 0xc6, 0x3c, 0x63, 0x8d, 0xc8, 0x68, 0x16, 0x23, 0x3f, 0x84, 0xdd, 0x4c, 0x0e,
	0x64, 0x9e, 0x72, 0x87, 0xf6, 0xd7, 0x92, 0x9f, 0xc0, 0x7e, 0x26, 0x79, 0x69, 0x48, 0x95, 0x58,
	0xff, 0x49, 0xdf, 0x23, 0xd8, 0xcf, 0x58, 0x6a, 0xca, 0xba, 0x17, 0xa6, 0x6a, 0x66, 0x22, 0x98,
	0x9b, 0xec, 0x23, 0x68, 0xfd, 0x3c, 0x50, 0x71, 0xde, 0xf3, 0x57, 0x06, 0xe5, 0x81, 0xf6, 0xf9,
	0x2d, 0xd4, 0x57, 0xc7, 0x2d, 0x9c, 0xf5, 0x1b, 0x71, 0xd6, 0xc7, 0xd5, 0x3a, 0xdd, 0xae, 0x17,
	0xe5, 0xb9, 0x0b, 0x07, 0x9b, 0xa3, 0xb4, 0x7f, 0xf9, 0x75, 0xc3, 0xd3, 0xea, 0xfc, 0xed, 0x29,
	0x5a, 0x5c, 0x5e, 0xbd, 0x2d, 0x04, 0x9b, 0x2f, 0x04, 0xfb, 0x5c, 0x08, 0xf6, 0xb2, 0x14, 0xa5,
	0xf9, 0x52, 0x94, 0x3e, 0x96, 0xa2, 0x74, 0xdf, 0xf1, 0x03, 0xf3, 0xf8, 0x34, 0x71, 0x3c, 0x15,
	0x76, 0x8b, 0x7a, 0xdf, 0x8b, 0x69, 0x37, 0x7f, 0x84, 0xb3, 0x18, 0xf5, 0xa4, 0x4a, 0x0f, 0xf1,
	0xe2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x6e, 0x79, 0xba, 0x9a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateVerse(ctx context.Context, in *MsgCreateVerse, opts ...grpc.CallOption) (*MsgCreateVerseResponse, error)
	// this line is used by starport scaffolding # proto/tx/rpc
	AddAssetToVerse(ctx context.Context, in *MsgAddAssetToVerse, opts ...grpc.CallOption) (*MsgAddAssetToVerseResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateVerse(ctx context.Context, in *MsgCreateVerse, opts ...grpc.CallOption) (*MsgCreateVerseResponse, error) {
	out := new(MsgCreateVerseResponse)
	err := c.cc.Invoke(ctx, "/imversed.verse.Msg/CreateVerse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddAssetToVerse(ctx context.Context, in *MsgAddAssetToVerse, opts ...grpc.CallOption) (*MsgAddAssetToVerseResponse, error) {
	out := new(MsgAddAssetToVerseResponse)
	err := c.cc.Invoke(ctx, "/imversed.verse.Msg/AddAssetToVerse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateVerse(context.Context, *MsgCreateVerse) (*MsgCreateVerseResponse, error)
	// this line is used by starport scaffolding # proto/tx/rpc
	AddAssetToVerse(context.Context, *MsgAddAssetToVerse) (*MsgAddAssetToVerseResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateVerse(ctx context.Context, req *MsgCreateVerse) (*MsgCreateVerseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVerse not implemented")
}
func (*UnimplementedMsgServer) AddAssetToVerse(ctx context.Context, req *MsgAddAssetToVerse) (*MsgAddAssetToVerseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAssetToVerse not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateVerse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateVerse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateVerse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imversed.verse.Msg/CreateVerse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateVerse(ctx, req.(*MsgCreateVerse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddAssetToVerse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddAssetToVerse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddAssetToVerse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imversed.verse.Msg/AddAssetToVerse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddAssetToVerse(ctx, req.(*MsgAddAssetToVerse))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imversed.verse.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVerse",
			Handler:    _Msg_CreateVerse_Handler,
		},
		{
			MethodName: "AddAssetToVerse",
			Handler:    _Msg_AddAssetToVerse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verse/tx.proto",
}

func (m *MsgCreateVerse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateVerse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateVerse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Icon) > 0 {
		i -= len(m.Icon)
		copy(dAtA[i:], m.Icon)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Icon)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateVerseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateVerseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateVerseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddAssetToVerse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddAssetToVerse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddAssetToVerse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerseCreator) > 0 {
		i -= len(m.VerseCreator)
		copy(dAtA[i:], m.VerseCreator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VerseCreator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AssetCreator) > 0 {
		i -= len(m.AssetCreator)
		copy(dAtA[i:], m.AssetCreator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssetCreator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AssetId) > 0 {
		i -= len(m.AssetId)
		copy(dAtA[i:], m.AssetId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssetId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AssetType) > 0 {
		i -= len(m.AssetType)
		copy(dAtA[i:], m.AssetType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AssetType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.VerseName) > 0 {
		i -= len(m.VerseName)
		copy(dAtA[i:], m.VerseName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.VerseName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddAssetToVerseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddAssetToVerseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddAssetToVerseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateVerse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Icon)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateVerseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddAssetToVerse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VerseName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AssetType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AssetId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AssetCreator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.VerseCreator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddAssetToVerseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateVerse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateVerse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateVerse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Icon", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Icon = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateVerseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateVerseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateVerseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddAssetToVerse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddAssetToVerse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddAssetToVerse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerseName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerseName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetCreator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetCreator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerseCreator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerseCreator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddAssetToVerseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddAssetToVerseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddAssetToVerseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
